//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmadoFurniture.Areas.AdminPaneli
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gelirler
    {
        public int GelirlerID { get; set; }
        public string GelirTurAdi { get; set; }
        public decimal GelirMiktari { get; set; }
        public System.DateTime Tarihi { get; set; }
        public int SiparisDetayID { get; set; }
        public int PersonelID { get; set; }
        public string Aciklama { get; set; }
    
        public virtual SiparisDetay SiparisDetay { get; set; }
    }
}
