//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmadoFurniture.Areas.AdminPaneli
{
    using System;
    using System.Collections.Generic;
    
    public partial class indirimler
    {
        public int indirimler1 { get; set; }
        public string indirimAdi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string Aciklama { get; set; }
    }
}
