//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmadoFurniture.Areas.AdminPaneli
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmadFurnitureDBEntities : DbContext
    {
        public AmadFurnitureDBEntities()
            : base("name=AmadFurnitureDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gelirler> Gelirler { get; set; }
        public virtual DbSet<GelirTurleri> GelirTurleri { get; set; }
        public virtual DbSet<Giderler> Giderler { get; set; }
        public virtual DbSet<GiderTurleri> GiderTurleri { get; set; }
        public virtual DbSet<indirimFiyatTanimlari> indirimFiyatTanimlari { get; set; }
        public virtual DbSet<indirimler> indirimler { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<MusteriAdresleri> MusteriAdresleri { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Personeller> Personeller { get; set; }
        public virtual DbSet<PersonelMaaslari> PersonelMaaslari { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetay { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tedarikciler> Tedarikciler { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<UrunResimleri> UrunResimleri { get; set; }
        public virtual DbSet<UrunStoklari> UrunStoklari { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
    }
}
