//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmadoFurniture.Areas.AdminPaneli
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriAdresleri
    {
        public int MusteriAdreslerID { get; set; }
        public string Adres { get; set; }
        public Nullable<int> MusteriID { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
